# Docker Compose configuration for go-services development environment
# This file sets up the necessary services for development and testing
version: "3.8"

services:
  # Go development container with the project code mounted
  golang:
    image: registry.windmaker.net:5005/a-castellano/limani/base_golang_1_24
    volumes:
      - ..:/app  # Mount the project directory into the container
    working_dir: /app
    command: tail -f /dev/null  # Keep container running
    environment:
      - REDIS_IP=172.20.0.20  # Set Redis IP for testing
    networks:
      go-services-net:
        ipv4_address: 172.20.0.10

  # Valkey server (Redis-compatible) for memory database testing
  valkey:
    image: registry.windmaker.net:5005/a-castellano/limani/base_valkey_server
    ports:
      - "6379:6379"  # Expose Redis port for external access
    networks:
      go-services-net:
        ipv4_address: 172.20.0.20

  # RabbitMQ server for message broker testing
  rabbitmq:
    image: registry.windmaker.net:5005/a-castellano/limani/base_rabbitmq_server
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # RabbitMQ management interface port
    networks:
      go-services-net:
        ipv4_address: 172.20.0.30

# Custom network configuration for service communication
networks:
  go-services-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16  # Private subnet for service communication
